### ISSUE TITLE
Get our OTA crawler to work (locally)

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/edit.tosdr.org#1160]
We had an OTA crawler on OVH but unfortunately it looks like that VPS was deleted due to a billing problem.
I'm now trying to run https://github.com/tosdr/tosdr-declarations on my laptop:
```
$ npx ota validate --services "Snapchat" --types "Terms of Service"


  Service declarations validation
    Snapchat
      ✔ valid declaration schema
      Terms of Service
        https://www.snap.com/en-US/terms
          ✔ fetchable URL
          1) selector matches an element in the source document
          [Tests skipped as content cannot be filtered]
          - filtered content has at least 100 characters
          [Tests skipped as content cannot be filtered]
          - content is consistent when fetched and filtered twice in a row


  2 passing (820ms)
  2 pending
  1 failing

  1) Service declarations validation
       Snapchat
         Terms of Service
           https://www.snap.com/en-US/terms
             selector matches an element in the source document:
     InaccessibleContentError: The documents cannot be accessed or their contents can not be selected:
 - The provided selector "main" matches an empty content in the web page at 'https://www.snap.com/en-US/terms'
      at extractFromHTML (file:///Users/michiel/gh/tosdr/tosdr-declarations/node_modules/@opentermsarchive/engine/src/archivist/extract/index.js:95:11)
      at extract (file:///Users/michiel/gh/tosdr/tosdr-declarations/node_modules/@opentermsarchive/engine/src/archivist/extract/index.js:36:10)
      at Context.checkSelector (file:///Users/michiel/gh/tosdr/tosdr-declarations/node_modules/@opentermsarchive/engine/scripts/declarations/validate/index.mocha.js:127:47)
      at process.processImmediate (node:internal/timers:478:21)
```

**Comment by michielbdejong** [comment]
I'm not getting good logs (setting `DEBUG=*` leads to a flood!) so I'll fork the repo and add some debug statements of my own.
Another thing I want to try is to find a crawl that currently does work, and test with that.

**Comment by michielbdejong** [comment]
Ah, I figured out two things:
* https://www.snap.com/en-US/terms is fetch with an empty `<main>` element which is then loaded through JS. Still, the error that the body is not found is weird.
* Following the OTA engine docs I found https://github.com/OpenTermsArchive/engine/issues/1100 so there it does work if you give it a selector that's actually in the document. 

However, even if I set the selector for https://www.snap.com/en-US/terms to `".theme--snapchat"` it's not matched so there's still some weirdness there.

Maybe I should find the list of declarations that do validate and work with that first

**Comment by michielbdejong** [comment]
`npx ota validate -o` -> 9202 passing

**Comment by michielbdejong** [comment]
-> #1161

**Comment by michielbdejong** [comment]
```
apt install ca-certificates fonts-liberation libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils
```

**Comment by michielbdejong** [comment]
Looking at https://github.com/OpenTermsArchive/engine/issues/1001 I found this:
```
apt-get update \
    && apt-get install -y wget gnupg \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /usr/share/keyrings/googlechrome-linux-keyring.gpg \
    && sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/googlechrome-linux-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-khmeros fonts-kacst fonts-freefont-ttf libxss1 \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*
```

**Comment by michielbdejong** [comment]
```
adduser crawler # pick random value for password, leave the room number etc empty
cp ~/.bashrc /home/crawler/
su crawler
```
now many of the commands need to be run as this user. will put together a working script next time I run this.

**Comment by michielbdejong** [comment]
Hm, still no usable sandbox. not sure what I'm doing wrong here, I'll create a server from scratch and try again

**Comment by michielbdejong** [comment]
Hm, with that I still get:
```
$ whoami
crawler
$ npx ota track --services "Musi"
2024-09-10 07:54:03 info                                                                              Start Open Terms Archive engine v2.2.1

2024-09-10 07:54:03 info                                                                              Examining 2 terms from 1 services for extraction…
2024-09-10 07:54:03 error                                                                             unhandledRejection: Failed to launch the browser process!
[6814:6814:0910/075403.221761:FATAL:zygote_host_impl_linux.cc(126)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/main/docs/linux/suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
[0910/075403.237495:ERROR:file_io_posix.cc(145)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
[0910/075403.237568:ERROR:file_io_posix.cc(145)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)


TROUBLESHOOTING: https://pptr.dev/troubleshooting

Error: Failed to launch the browser process!
[6814:6814:0910/075403.221761:FATAL:zygote_host_impl_linux.cc(126)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/main/docs/linux/suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
[0910/075403.237495:ERROR:file_io_posix.cc(145)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
[0910/075403.237568:ERROR:file_io_posix.cc(145)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)


TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at ChildProcess.onClose (/home/crawler/engine/node_modules/@puppeteer/browsers/lib/cjs/launch.js:310:24)
    at ChildProcess.emit (node:events:531:35)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
```

**Comment by michielbdejong** [comment]
Now trying Ubuntu 20.04 with:
```
apt install fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-khmeros fonts-kacst fonts-freefont-ttf libxss1 
apt install libatk1.0-0

**Comment by michielbdejong** [comment]
```
sudo apt install -y ca-certificates fonts-liberation libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils

**Comment by michielbdejong** [comment]
Looks like maybe the key is to use Ubuntu-20.04 and not Ubuntu-24.04!

**Comment by michielbdejong** [comment]
So, I think the instructions that work are:
* ssh into a fresh Ubuntu 20.04 box. Then:
```
adduser crawler
```
(pick a password that will be used for sudo later)
(leave room number etc empty)
```
usermod -aG sudo crawler
su crawler
sudo apt-get update
apt install -y ca-certificates fonts-liberation libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils
```
(this will require the sudo password)
```
cd ~
git clone https://github.com/tosdr/ota-engine engine
git clone https://github.com/tosdr/tosdr-declarations declarations
cd declarations
git checkout removals
git pull
cd ../engine
ln -s ../declarations/declarations
mkdir data
cd data
git clone https://github.com/tosdr/tosdr-versions versions
git clone https://github.com/tosdr/tosdr-snapshots snapshots
cd ..
wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
source ~/.bashrc
nvm install 20
nvm use 20
npm install
npx ota track --services "Musi"
```

**Comment by michielbdejong** [comment]
It's working!

Next issue: it's VERY slow, checking Musi which has two very simple documents takes several minutes!

It seems to be due to the simple-git scheduler which keeps saying 'Schedule attempt ignored.'
Or maybe it's just fetching 5 times in a row, with timeouts inbetween?
