### ISSUE TITLE
db:seed fails in docker compose

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/edit.tosdr.org#1165]
```
michiel-2:edit.tosdr.org michiel$ docker ps
CONTAINER ID   IMAGE                             COMMAND                  CREATED              STATUS                        PORTS                                NAMES
75abe8fad7c5   postgres:11.5-alpine              "docker-entrypoint.s…"   About a minute ago   Up About a minute (healthy)   127.0.0.1:5432->5432/tcp             db
cc08634fcb24   edittosdrorg-web                  "bash docker-entrypo…"   About a minute ago   Up About a minute             0.0.0.0:9090->3000/tcp               edittosdrorg-web-1
7f671ddcea51   adminer                           "entrypoint.sh php -…"   About a minute ago   Up About a minute             0.0.0.0:1337->8080/tcp               edittosdrorg-adminer-1
6ffd99f5b963   hypothesis/elasticsearch:latest   "/usr/local/bin/dock…"   About a minute ago   Up About a minute             127.0.0.1:9200->9200/tcp, 9300/tcp   edittosdrorg-elasticsearch-1
michiel-2:edit.tosdr.org michiel$ docker exec -it edittosdrorg-web-1 rails db:seed
TOSBackDoc loaded
Initializing the background worker with 16 threads
[Sessions] Sessions won't be captured without a valid release
   (1.8ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Starting seeding...
Seeding users
   (0.3ms)  BEGIN
  User Create (5.6ms)  INSERT INTO "users" ("email", "encrypted_password", "created_at", "updated_at", "username", "admin", "curator", "confirmed_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING "id"  [["email", "admin@selfhosted.tosdr.org"], ["encrypted_password", "$2a$11$aV1IgJ6ZzDLbsE9cx49.a.q/2V.W0sU.W6ny8BugOtsFm8Ivd5w72"], ["created_at", "2024-09-12 08:01:02.768641"], ["updated_at", "2024-09-12 08:01:02.768641"], ["username", "tosdr_admin"], ["admin", true], ["curator", true], ["confirmed_at", "2024-09-12 08:01:02.768182"]]
   (0.3ms)  ROLLBACK
rails aborted!
ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_users_on_email"
DETAIL:  Key (email)=(admin@selfhosted.tosdr.org) already exists.
/usr/local/bundle/gems/rack-mini-profiler-3.1.0/lib/patches/db/pg.rb:110:in `async_exec'
/usr/local/bundle/gems/rack-mini-profiler-3.1.0/lib/patches/db/pg.rb:110:in `async_exec'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/connection_adapters/postgresql_adapter.rb:675:in `block (2 levels) in exec_no_cache'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/connection_adapters/postgresql_adapter.rb:674:in `block in exec_no_cache'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/connection_adapters/abstract_adapter.rb:728:in `block (2 levels) in log'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/connection_adapters/abstract_adapter.rb:727:in `block in log'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/connection_adapters/abstract_adapter.rb:718:in `log'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/connection_adapters/postgresql_adapter.rb:673:in `exec_no_cache'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/connection_adapters/postgresql_adapter.rb:656:in `execute_and_clear'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `exec_query'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/connection_adapters/abstract/database_statements.rb:135:in `exec_insert'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:132:in `exec_insert'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/connection_adapters/abstract/database_statements.rb:166:in `insert'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/connection_adapters/abstract/query_cache.rb:22:in `insert'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/persistence.rb:375:in `_insert_record'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/persistence.rb:932:in `_create_record'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/counter_cache.rb:166:in `_create_record'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/locking/optimistic.rb:79:in `_create_record'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/attribute_methods/dirty.rb:211:in `_create_record'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/callbacks.rb:331:in `block in _create_record'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/callbacks.rb:135:in `run_callbacks'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/callbacks.rb:825:in `_run_create_callbacks'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/callbacks.rb:331:in `_create_record'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/timestamp.rb:110:in `_create_record'
/usr/local/bundle/gems/bullet-7.0.7/lib/bullet/active_record60.rb:6:in `_create_record'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/persistence.rb:905:in `create_or_update'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/callbacks.rb:327:in `block in create_or_update'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/autosave_association.rb:366:in `around_save_collection_association'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/callbacks.rb:139:in `run_callbacks'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/callbacks.rb:825:in `_run_save_callbacks'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/callbacks.rb:327:in `create_or_update'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/timestamp.rb:128:in `create_or_update'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/persistence.rb:470:in `save'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/validations.rb:47:in `save'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/transactions.rb:314:in `block in save'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `block in transaction'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `transaction'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/transactions.rb:212:in `transaction'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/transactions.rb:314:in `save'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/suppressor.rb:44:in `save'
/usr/local/bundle/gems/devise-4.9.2/lib/devise/models/confirmable.rb:97:in `block in confirm'
/usr/local/bundle/gems/devise-4.9.2/lib/devise/models/confirmable.rb:239:in `pending_any_confirmation'
/usr/local/bundle/gems/devise-4.9.2/lib/devise/models/confirmable.rb:80:in `confirm'
/usr/src/edit.tosdr.org/db/seeds.rb:22:in `block in <top (required)>'
/usr/src/edit.tosdr.org/db/seeds.rb:21:in `each'
/usr/src/edit.tosdr.org/db/seeds.rb:21:in `<top (required)>'
/usr/local/bundle/gems/railties-6.0.6.1/lib/rails/engine.rb:557:in `load'
/usr/local/bundle/gems/railties-6.0.6.1/lib/rails/engine.rb:557:in `block in load_seed'
/usr/local/bundle/gems/railties-6.0.6.1/lib/rails/engine.rb:675:in `with_inline_jobs'
/usr/local/bundle/gems/railties-6.0.6.1/lib/rails/engine.rb:557:in `load_seed'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/tasks/database_tasks.rb:440:in `load_seed'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/railties/databases.rake:331:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/sentry-ruby-5.9.0/lib/sentry/rake.rb:26:in `execute'
/usr/local/bundle/gems/railties-6.0.6.1/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/usr/local/bundle/gems/railties-6.0.6.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/usr/local/bundle/gems/railties-6.0.6.1/lib/rails/command.rb:48:in `invoke'
/usr/local/bundle/gems/railties-6.0.6.1/lib/rails/commands.rb:18:in `<top (required)>'
/usr/src/edit.tosdr.org/bin/rails:9:in `require'
/usr/src/edit.tosdr.org/bin/rails:9:in `<top (required)>'
/usr/local/bundle/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
/usr/local/bundle/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
/usr/local/bundle/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
/usr/local/bundle/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
/usr/local/bundle/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
/usr/local/bundle/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
/usr/local/bundle/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
<internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/usr/src/edit.tosdr.org/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'

Caused by:
PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_users_on_email"
DETAIL:  Key (email)=(admin@selfhosted.tosdr.org) already exists.
/usr/local/bundle/gems/rack-mini-profiler-3.1.0/lib/patches/db/pg.rb:110:in `async_exec'
/usr/local/bundle/gems/rack-mini-profiler-3.1.0/lib/patches/db/pg.rb:110:in `async_exec'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/connection_adapters/postgresql_adapter.rb:675:in `block (2 levels) in exec_no_cache'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/connection_adapters/postgresql_adapter.rb:674:in `block in exec_no_cache'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/connection_adapters/abstract_adapter.rb:728:in `block (2 levels) in log'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/connection_adapters/abstract_adapter.rb:727:in `block in log'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/connection_adapters/abstract_adapter.rb:718:in `log'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/connection_adapters/postgresql_adapter.rb:673:in `exec_no_cache'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/connection_adapters/postgresql_adapter.rb:656:in `execute_and_clear'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `exec_query'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/connection_adapters/abstract/database_statements.rb:135:in `exec_insert'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:132:in `exec_insert'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/connection_adapters/abstract/database_statements.rb:166:in `insert'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/connection_adapters/abstract/query_cache.rb:22:in `insert'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/persistence.rb:375:in `_insert_record'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/persistence.rb:932:in `_create_record'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/counter_cache.rb:166:in `_create_record'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/locking/optimistic.rb:79:in `_create_record'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/attribute_methods/dirty.rb:211:in `_create_record'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/callbacks.rb:331:in `block in _create_record'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/callbacks.rb:135:in `run_callbacks'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/callbacks.rb:825:in `_run_create_callbacks'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/callbacks.rb:331:in `_create_record'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/timestamp.rb:110:in `_create_record'
/usr/local/bundle/gems/bullet-7.0.7/lib/bullet/active_record60.rb:6:in `_create_record'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/persistence.rb:905:in `create_or_update'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/callbacks.rb:327:in `block in create_or_update'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/autosave_association.rb:366:in `around_save_collection_association'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/callbacks.rb:139:in `run_callbacks'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/callbacks.rb:825:in `_run_save_callbacks'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/callbacks.rb:327:in `create_or_update'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/timestamp.rb:128:in `create_or_update'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/persistence.rb:470:in `save'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/validations.rb:47:in `save'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/transactions.rb:314:in `block in save'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `block in transaction'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/usr/local/bundle/gems/activesupport-6.0.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `transaction'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/transactions.rb:212:in `transaction'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/transactions.rb:314:in `save'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/suppressor.rb:44:in `save'
/usr/local/bundle/gems/devise-4.9.2/lib/devise/models/confirmable.rb:97:in `block in confirm'
/usr/local/bundle/gems/devise-4.9.2/lib/devise/models/confirmable.rb:239:in `pending_any_confirmation'
/usr/local/bundle/gems/devise-4.9.2/lib/devise/models/confirmable.rb:80:in `confirm'
/usr/src/edit.tosdr.org/db/seeds.rb:22:in `block in <top (required)>'
/usr/src/edit.tosdr.org/db/seeds.rb:21:in `each'
/usr/src/edit.tosdr.org/db/seeds.rb:21:in `<top (required)>'
/usr/local/bundle/gems/railties-6.0.6.1/lib/rails/engine.rb:557:in `load'
/usr/local/bundle/gems/railties-6.0.6.1/lib/rails/engine.rb:557:in `block in load_seed'
/usr/local/bundle/gems/railties-6.0.6.1/lib/rails/engine.rb:675:in `with_inline_jobs'
/usr/local/bundle/gems/railties-6.0.6.1/lib/rails/engine.rb:557:in `load_seed'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/tasks/database_tasks.rb:440:in `load_seed'
/usr/local/bundle/gems/activerecord-6.0.6.1/lib/active_record/railties/databases.rake:331:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/sentry-ruby-5.9.0/lib/sentry/rake.rb:26:in `execute'
/usr/local/bundle/gems/railties-6.0.6.1/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/usr/local/bundle/gems/railties-6.0.6.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/usr/local/bundle/gems/railties-6.0.6.1/lib/rails/command.rb:48:in `invoke'
/usr/local/bundle/gems/railties-6.0.6.1/lib/rails/commands.rb:18:in `<top (required)>'
/usr/src/edit.tosdr.org/bin/rails:9:in `require'
/usr/src/edit.tosdr.org/bin/rails:9:in `<top (required)>'
/usr/local/bundle/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
/usr/local/bundle/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
/usr/local/bundle/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
/usr/local/bundle/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
/usr/local/bundle/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
/usr/local/bundle/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
/usr/local/bundle/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
<internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/usr/src/edit.tosdr.org/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
Shutting down background worker
Killing session flusher
michiel-2:edit.tosdr.org michiel$

**Comment by madoleary** [comment]
If you still experience issues, you can try running db:reset and doing the
seed again.
